#!/bin/bash
#SBATCH -o /home/users/giobbe.forni/gen_red/paint/assemblies/vicia/myjob.%j.%N.out
#SBATCH -D /home/users/giobbe.forni/gen_red/paint/assemblies/vicia
#SBATCH -J assemble_vicia
#SBATCH --get-user-env
#SBATCH -p bigmem
#SBATCH --nodes=1
#SBATCH -c 32                    # Number of cores per task
#SBATCH --mem-per-cpu 20000       #  Mem for each core
#SBATCH --time=2-00:00:00
#SBATCH --account=gen_red

module load Mlnx/hpcx

cd /home/users/giobbe.forni/gen_red/paint/assemblies/vicia

Trinity --samples_file ../../vicia_samples.txt --CPU 32 --max_memory 600G --seqType fq --output trinity_vicia --quality_trimming_params "ILLUMINACLIP:ILLUMINACLIP:/gpfs/home/projects/gen_red/cartella/env/paint/share/trimmomatic-0.39-2/adapters/TruSeq3-PE.fa:2:30:10:2:TRUE SLIDINGWINDOW:28:30 LEADING:28 TRAILING:28 MINLEN:99" 2>&1 | tee run_trinity.log
