#!/bin/bash
#SBATCH -o /home/users/giobbe.forni/gen_red/paint/abundances/crema/myjob.%j.%N-%t.out
#SBATCH -D /home/users/giobbe.forni/gen_red/paint/abundances/crema/myjob.%j.%N-%t.err
#SBATCH -J abundances_crema
#SBATCH --get-user-env
#SBATCH -p light
#SBATCH --nodes=1
#SBATCH -c 24                     # Number of cores per task
#SBATCH --mem-per-cpu 2000        #  Mem for each core
#SBATCH --time=2-00:00:00
#SBATCH --account=gen_red

module load Mlnx/hpcx

cd /home/users/giobbe.forni/gen_red/paint/

align_and_estimate_abundance.pl --seqType fq  --samples_file crema_samples.txt --transcripts assemblies/crema/crema.Trinity.fasta --est_method RSEM  --aln_method bowtie --trinity_mode --output_dir abundances/crema/ --prep_reference
