#!/bin/bash
#SBATCH -o /home/users/giobbe.forni/gen_red/paint/assemblies/crema/myjob.%j.%N.out
#SBATCH -D /home/users/giobbe.forni/gen_red/paint/assemblies/crema
#SBATCH -J assemble_crema
#SBATCH --get-user-env
#SBATCH -p bigmem
#SBATCH --nodes=1
#SBATCH -c 32			# Number of cores per task
#SBATCH --mem-per-cpu 20000	#  Mem for each core
#SBATCH --time=2-00:00:00
#SBATCH --account=gen_red

module load Mlnx/hpcx

cd /home/users/giobbe.forni/gen_red/paint/assemblies/crema

Trinity --samples_file crema_samples.txt --CPU 32 --max_memory 600G --seqType fq --output trinity_crema 2>&1 | tee run_trinity.log
